"use client";

import { Check, Code2, Copy, Laptop, Puzzle, Settings2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export function ExtensionGuide({ onOpenSettings }: { onOpenSettings: () => void }) {
  const copyFolder = () => { void navigator.clipboard?.writeText("extension/"); };
  return <section className="full-view extension-view"><div className="extension-hero"><div className="extension-hero-copy"><div className="extension-icon"><Puzzle size={24} /></div><p className="eyebrow">Draftwise extension</p><h1>Helpful, wherever you write.</h1><p>Bring the same local rules to textareas, inputs, and contenteditable fields across the web. The service worker keeps optional AI requests away from page-facing code.</p><div className="extension-hero-actions"><Button onClick={copyFolder}><Copy size={15} /> Copy install folder</Button><Button variant="outline" onClick={onOpenSettings}><Settings2 size={15} /> Extension settings</Button></div></div><div className="extension-preview"><div className="fake-browser-bar"><span /><span /><span /><strong>docs.example.com</strong></div><div className="fake-page"><div className="fake-page-copy"><span className="fake-line wide" /><span className="fake-line" /><span className="fake-line short" /><span className="fake-underline">The draft is ready to review.</span></div><div className="fake-assistant"><div className="fake-assistant-header"><span className="mini-mark" /> <strong>draftwise</strong><span className="fake-close">×</span></div><p>One spelling suggestion</p><div className="fake-fix"><span>recieve</span><span aria-hidden="true">→</span><strong>receive</strong></div><button type="button">Accept</button></div></div></div></div><div className="extension-grid"><div className="extension-card"><div className="extension-card-icon"><Laptop size={18} /></div><h3>Install with least privilege</h3><p>Open <code>chrome://extensions</code>, turn on Developer mode, choose “Load unpacked”, select the <code>extension</code> folder, and grant access only to sites you choose.</p><span className="extension-card-note"><Check size={13} /> Optional host permissions</span></div><div className="extension-card"><div className="extension-card-icon"><ShieldCheck size={18} /></div><h3>Private by design</h3><p>Sensitive fields are skipped. Local analysis runs in the page; optional AI runs in the Manifest V3 service worker. API keys never enter page scripts.</p><span className="extension-card-note"><Check size={13} /> No page analytics</span></div><div className="extension-card"><div className="extension-card-icon"><Code2 size={18} /></div><h3>One shared engine</h3><p>The extension bundle is built from the same grammar and provider packages as the web editor, so rule IDs and behavior stay aligned.</p><span className="extension-card-note"><Check size={13} /> Build-time shared packages</span></div></div></section>;
}
